# -*- coding: utf-8 -*-

SKILL_GO_ON							= "SKILL_GO_ON"
SKILL_IS_CASTING					= "SKILL_IS_CASTING"
SKILL_IN_CD							= "SKILL_IN_CD"
SKILL_TOO_NEAR						= "SKILL_TOO_NEAR"
SKILL_TOO_FAR						= "SKILL_TOO_FAR"
SKILL_CASTER_STATUS_WRONG			= "SKILL_CASTER_STATUS_WRONG"
SKILL_TARGET_TYPE_ERR				= "SKILL_TARGET_TYPE_ERR"
SKILL_TARGET_IS_NOT_DEAD			= "SKILL_TARGET_IS_NOT_DEAD"
SKILL_TARGET_POS_ERR				= "SKILL_TARGET_POS_ERR"
SKILL_STATUS_SYS_ERR				= "SKILL_STATUS_SYS_ERR"